### ISSUE TITLE
using epsg.io transformer result is different to using proj4 string for EPSG 24879 PSAD56 UTM zone 19S

### ISSUE THREAD

**Issue by TimPrpllerLiu** [maptiler/epsg.io#201]
Hi,

I'm trying to use epsg.io transformer to check the PSAD56/UTM zone 19S projection, but found the converted result is different. Can anyone help?
What I see are:
1. in EPSG.io https://epsg.io/transform#s_srs=4326&t_srs=24879&x=-70.4633690&y=-27.4667269, I got E/N 355591.0359 / 6961392.313
2. by using proj4js with proj4 string, I got E/N:	 355608.92723451636, 	6961356.305929353, 652
3. by using gdal cs2cs with proj4 string, I got same as 2.
So I know the PSAD56 datum has different toWGS84 parameters, but UTM zone 19S is the one the same as EPSG:4248 definition, so where is the difference come from? 

Some examples I had:
cs2cs +proj=latlon +datum=WGS84 +to +proj=utm +zone=19 +south +ellps=intl +towgs84=-288,175,-376,0,0,0,0 +units=m +no_defs
and I also noticed when using proj4js with epsg 24879, it returns error.

Also I'm using  proj4@2.3.15.

Thank you in advance for checking it!

**Comment by TomPohys** [comment]
Hi, the difference is caused by the used transformation. The epsg.io/transform has the default `Using best available transformer` which tries to use the best available transformation for your coordinates.

If you use [EPSG:24879](https://epsg.io/24879) with default transformation (selected in the list of transformations - [EPSG:1201](https://epsg.io/1201)) then you get the proj4js or cs2cs values. But if you use better transformation for your coordinates ([EPSG:6973](https://epsg.io/6973)) then you get better precision (and if you paste the [proj4](https://epsg.io/24879-6972.proj4) string from https://epsg.io/24879-6972 (`+proj=utm +zone=19 +south +ellps=intl +towgs84=-328,340,-329,0,0,0,0 +units=m +no_defs +type=crs`) then you will get the same values for /transform and cs2cs

**Comment by TimPrpllerLiu** [comment]
Thank you Tom, this makes sense and help heaps a lot! So the towgs84 parameters are different!
